version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_DATABASE: marieteam
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - mynet

volumes:
  mysql_data:

networks:
  mynet:
